### ISSUE TITLE
CV_ExpLoopEnvelope2 double knee/bump

### ISSUE THREAD

**Issue by mxmilkiib** [ryukau/LV2Plugins#27] opened 2020-07-11 17:54 UTC
I'm trying to full control CV_ExpLoopEnvelope2 using CV with all internal controls (apart from gain) set to 0, but I'm still getting a double bump. [Here's a video](https://www.youtube.com/watch?v=oSizZ6tQwu8). The second envelope is also suffering a similar problem, though it has level up internally rather than via CV, swapped with the gain.

**Comment by ryukau** [comment] 2020-07-12 02:47
Fixed in latest commit.

The cause was resetting internal timer on release in trigger mode. Trigger mode is set when `Loop Start` to min and `Loop End` to max.

**Closed by ryukau** 2020-07-12 02:47 UTC
